#!/usr/bin/env python
import os
import pwd
import time
import argparse

count = 20  # default count = 20

file_list = []


def find_bigfiles(sdir, count):
    for (path, dir, files) in os.walk(sdir):
        for filename in files:
            fullname = path + "/" + filename
            try:
                filestat = os.stat(fullname)
                _ltime = time.localtime(filestat.st_mtime)
                _mtime = time.strftime("%Y/%m/%d-%H:%M", _ltime)
                _user = pwd.getpwuid(filestat.st_uid).pw_name
                _size = filestat.st_size / 1024 / 1024
                _perm = oct(filestat.st_mode)[-3:]
                t_file = (fullname, _mtime, _perm, _user, _size)

                file_list.append(t_file)
            except (FileNotFoundError, PermissionError):
                pass

    sort_files = sorted(file_list, key=lambda x: (-x[4]))
    big_files = sort_files[:count]
    # print(sort_files[:count])

    for f, t, p, u, s in big_files:
        # mtime = t(time)
        print(
            "File:{0:50s} Mtime:{1:17s} Perm:{2:4s} User:{3:<10s} Size:{4:.3f} Mbyte".format(
                f, t, p, u, s
            )
        )


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-s", "--sdir", type=str, help="디렉터리")
    parser.add_argument("-n", "--count", type=int, help="갯수")
    args = parser.parse_args()

    if args.sdir is None or type(args.count) != int:
        print("Usage: python big20.py -s {dir} -n {count}")
    else:
        find_bigfiles(args.sdir, args.count)
